FROM wordpress:6.7-php8.3-apache
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp
ENV WP_CLI_ALLOW_ROOT=1
